###############################################################################
# Instance
###############################################################################

output "instance_name" {
  description = "Name of the Lightsail instance."
  value       = one(aws_lightsail_instance.this[*].name)
}

output "instance_arn" {
  description = "ARN of the Lightsail instance."
  value       = one(aws_lightsail_instance.this[*].arn)
}

output "instance_public_ip_address" {
  description = "Public IP address assigned to the instance."
  value       = one(aws_lightsail_instance.this[*].public_ip_address)
}

output "instance_private_ip_address" {
  description = "Private IP address assigned to the instance."
  value       = one(aws_lightsail_instance.this[*].private_ip_address)
}

output "instance_ipv6_addresses" {
  description = "IPv6 addresses assigned to the instance."
  value       = one(aws_lightsail_instance.this[*].ipv6_addresses)
}

output "instance_username" {
  description = "Default user name for connecting to the instance."
  value       = one(aws_lightsail_instance.this[*].username)
}

output "key_pair_name" {
  description = "Name of the key pair attached to the instance, whether created here or supplied."
  value       = local.key_pair_name
}

output "key_pair_fingerprint" {
  description = "Fingerprint of the key pair created by this module."
  value       = one(aws_lightsail_key_pair.this[*].fingerprint)
}

output "key_pair_private_key" {
  description = "Private key generated by Lightsail when key_pair is created without a public_key."
  value       = one(aws_lightsail_key_pair.this[*].private_key)
  sensitive   = true
}

output "disk_names" {
  description = "Names of the block storage disks, keyed by the disks input key."
  value       = { for key, disk in aws_lightsail_disk.this : key => disk.name }
}

output "disk_arns" {
  description = "ARNs of the block storage disks, keyed by the disks input key."
  value       = { for key, disk in aws_lightsail_disk.this : key => disk.arn }
}

output "static_ip_name" {
  description = "Name of the static IP allocated for the instance."
  value       = one(aws_lightsail_static_ip.this[*].name)
}

output "static_ip_address" {
  description = "Static IP address allocated for the instance. Point DNS records here."
  value       = one(aws_lightsail_static_ip.this[*].ip_address)
}

###############################################################################
# Load balancer
###############################################################################

output "lb_name" {
  description = "Name of the load balancer."
  value       = one(aws_lightsail_lb.this[*].name)
}

output "lb_arn" {
  description = "ARN of the load balancer."
  value       = one(aws_lightsail_lb.this[*].arn)
}

output "lb_dns_name" {
  description = "DNS name of the load balancer."
  value       = one(aws_lightsail_lb.this[*].dns_name)
}

output "lb_certificate_name" {
  description = "Name of the load balancer TLS certificate."
  value       = one(aws_lightsail_lb_certificate.this[*].name)
}

output "lb_certificate_domain_validation_records" {
  description = "DNS records that must be published to validate the load balancer certificate before it can be attached."
  value       = one(aws_lightsail_lb_certificate.this[*].domain_validation_records)
}

###############################################################################
# Database
###############################################################################

output "database_name" {
  description = "Name of the managed relational database."
  value       = one(aws_lightsail_database.this[*].relational_database_name)
}

output "database_arn" {
  description = "ARN of the managed relational database."
  value       = one(aws_lightsail_database.this[*].arn)
}

output "database_master_endpoint_address" {
  description = "Endpoint address of the managed relational database."
  value       = one(aws_lightsail_database.this[*].master_endpoint_address)
}

output "database_master_endpoint_port" {
  description = "Endpoint port of the managed relational database."
  value       = one(aws_lightsail_database.this[*].master_endpoint_port)
}

###############################################################################
# Bucket
###############################################################################

output "bucket_name" {
  description = "Name of the object storage bucket."
  value       = one(aws_lightsail_bucket.this[*].name)
}

output "bucket_arn" {
  description = "ARN of the object storage bucket."
  value       = one(aws_lightsail_bucket.this[*].arn)
}

output "bucket_url" {
  description = "URL of the object storage bucket."
  value       = one(aws_lightsail_bucket.this[*].url)
}

output "bucket_access_key_id" {
  description = "Access key ID created for the bucket."
  value       = one(aws_lightsail_bucket_access_key.this[*].access_key_id)
}

output "bucket_secret_access_key" {
  description = "Secret access key created for the bucket."
  value       = one(aws_lightsail_bucket_access_key.this[*].secret_access_key)
  sensitive   = true
}

###############################################################################
# Certificate and distribution
###############################################################################

output "certificate_name" {
  description = "Name of the Lightsail certificate."
  value       = one(aws_lightsail_certificate.this[*].name)
}

output "certificate_arn" {
  description = "ARN of the Lightsail certificate."
  value       = one(aws_lightsail_certificate.this[*].arn)
}

output "certificate_domain_validation_options" {
  description = "DNS records that must be published to validate the Lightsail certificate."
  value       = one(aws_lightsail_certificate.this[*].domain_validation_options)
}

output "distribution_name" {
  description = "Name of the CDN distribution."
  value       = one(aws_lightsail_distribution.this[*].name)
}

output "distribution_arn" {
  description = "ARN of the CDN distribution."
  value       = one(aws_lightsail_distribution.this[*].arn)
}

output "distribution_domain_name" {
  description = "Domain name of the CDN distribution."
  value       = one(aws_lightsail_distribution.this[*].domain_name)
}

output "distribution_status" {
  description = "Status of the CDN distribution."
  value       = one(aws_lightsail_distribution.this[*].status)
}

###############################################################################
# Container service
###############################################################################

output "container_service_name" {
  description = "Name of the container service."
  value       = one(aws_lightsail_container_service.this[*].name)
}

output "container_service_arn" {
  description = "ARN of the container service."
  value       = one(aws_lightsail_container_service.this[*].arn)
}

output "container_service_url" {
  description = "Public URL of the container service."
  value       = one(aws_lightsail_container_service.this[*].url)
}

output "container_service_private_domain_name" {
  description = "Private domain name of the container service."
  value       = one(aws_lightsail_container_service.this[*].private_domain_name)
}

output "container_service_deployment_version" {
  description = "Version number of the current container service deployment."
  value       = one(aws_lightsail_container_service_deployment_version.this[*].version)
}

###############################################################################
# DNS and alarms
###############################################################################

output "domain_name" {
  description = "Name of the Lightsail DNS zone."
  value       = one(aws_lightsail_domain.this[*].domain_name)
}

output "domain_arn" {
  description = "ARN of the Lightsail DNS zone."
  value       = one(aws_lightsail_domain.this[*].arn)
}

output "alarm_names" {
  description = "Names of the Lightsail alarms, keyed by the alarms input key."
  value       = { for key, alarm in awscc_lightsail_alarm.this : key => alarm.alarm_name }
}

output "alarm_arns" {
  description = "ARNs of the Lightsail alarms, keyed by the alarms input key."
  value       = { for key, alarm in awscc_lightsail_alarm.this : key => alarm.alarm_arn }
}
